import Head from 'next/head'
import { server } from '../src/config'
import styles from '../styles/Home.module.css'

const CLIENT_ID = "a70d66f34db04d7e86f52acc1615ec37"
const REDIRECT_URI = `${server}/callback/`
const AUTH_ENDPOINT = "https://accounts.spotify.com/authorize"
const RESPONSE_TYPE = "token"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href={`${AUTH_ENDPOINT}?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&response_type=${RESPONSE_TYPE}`}>Login to Spotify</a>
    </div>
  )
}
